config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root 'posts#index'
  devise_for :users
  resources :posts
  resources :categories do
    resources :posts
  end

  get 'allresult' => 'posts#allresult'

  resources :users
  mount Commontator::Engine => '/commontator'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	validates :category, presence: true
	validates :title, presence: true
	validates :body, presence: true
	acts_as_commontable



	def self.search(query)
		where("title like ?", "%#{query}%")
	end




end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	acts_as_commontator

	 has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  @category = Category.new()
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password) }
   end
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
      @category = Category.new
  end

  # GET /categories/1/edit
  def edit
      @category = Category.new
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    if user_signed_in?
      @post.user_id = current_user.id
    
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
      else
      raise 'You arent signed in'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
  end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index

    @posts = Post.all.order('created_at DESC')
    if @posts.count == 0

    end
end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def allresult
    if params[:search]
      @posts = Post.search(params[:search])
    else 
      @posts = Post.all
    end
 end

  # POST /posts
  # POST /posts.json
  def create
    
    if not user_signed_in?
      redirect_to new_user_session_path, :flash => { :errors => "Please Sign In" } and return

    else
      @post = Post.new(post_params)
      @post.user_id = current_user.id
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.user_id != current_user
      raise 'You dont bullshit me'
    else
      
    
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user_id = current_user
    else
      raise 'You cant do that shit bruh'
    end
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @post = @user.posts
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
	def categoryoptions
		s = ''
		Category.all.each do |category|
			s << "<option value = '#{category.id}'>#{category.name}</option>"
		end
		s.html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<% if user_signed_in? && current_user.id ==5 %>
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% else %>
<h1>You are not me</h1>
<% end %>

app/views/categories/index.html.erb
<% if user_signed_in? && current_user.id ==5 %>
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>
<% else %>
<h1>You are not me</h1>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<%= link_to 'Back', categories_path %>

app/views/layouts/_header.html.erb
<nav class="navbar fixed navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href = '/'>WRAPP MUIC</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><%= link_to "Home", "/" %></li>
        <% if user_signed_in? %>
          <li><%= link_to "All Posts", posts_path %></li>
          <li><%= link_to current_user.first_name,  user_path(id: current_user.id) %></li>
          <li><%= link_to "Log Out",destroy_user_session_path, :method => :delete  %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Create Account",new_user_registration_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></li>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/sign_in"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></li>
      <% end %>
      </ul>
      <div>
          <%= form_tag(
          allresult_path, :method => "get", class: "container navbar-form navbar-right", role:"search") do %>
          <div class="form-group">
          <%= text_field_tag :search,
          params[:search], style: "color:black",placeholder: "Search.." %>
        </div>
        <% end %>
      </div>
      </form>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select 'category_id',categoryoptions,multiple:
    true,class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
	<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= post.title %></h3>
  </div>
  <div class="panel-body">
    <%= post.body %>
  </div>
</div>

app/views/posts/allresult.html.erb
<p id="notice"><%= notice %></p>




<% @posts.each do |post| %>
<div class="panel panel-default">
  <div class="panel-body">
    <h2><%= link_to post.title, post %></h2>

    <br>
    A Lovely <%= post.category.name %>
    <p class="date" align ="right">Submitted <%= time_ago_in_words(post.created_at) %> ago by <%= link_to post.user.first_name, user_path(id: post.user_id) %></p>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>



<% if @posts.count != 0 %>
<% @posts.each do |post| %>
<div class="panel panel-default">
  <div class="panel-body">
    <h2><%= link_to post.title, post %></h2>

    <br>
    A Lovely <%= post.category.name %>
    <p class="date" align ="right">Submitted <%= time_ago_in_words(post.created_at) %> ago by <%= link_to post.user.first_name, user_path(id: post.user_id) %></p>
  </div>
</div>
<% end %>

<% else %> 
<p align = 'center'> Add a new post! </p>
<%end%>

app/views/posts/new.html.erb
<div class = "col-md-4"></div>
<div class = "col-md-4" align = 'center' >
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>
<div class = "col-md-4"></div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><h2><%= @post.title %><h2></h3>
  </div>
  <div class="panel-body">
    <%= @post.body %>
  </div>
</div>
<p align='right'>
	Submitted <%= time_ago_in_words(@post.created_at) %> ago
</p>
<%= commontator_thread(@post) %>

<% if user_signed_in? %>
<% if @post.user_id = current_user.id %>
	<%= link_to 'Back', posts_path %>
<% else %>
		<%= link_to 'Edit', edit_post_path(@post) %>
		<%= link_to 'Delete', post_path(@post.id),:method => :delete %>
		<%= link_to 'Back', posts_path %>
<% end %>
<% else %>
	<%= link_to 'Back', posts_path %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-body">
    <p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

  </div>
</div>



<%= render @post %>